image: docker:19.03.1

stages:
  - build
  - push

services:
  - docker:19.03.1-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login --password-stdin -u $CI_REGISTRY_USER $CI_REGISTRY


### BUILD ###
build:
  stage: build
  only:
    - master
  script:
    - docker pull $CI_REGISTRY_IMAGE:build-cache || true
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:build-cache
      --tag $CI_REGISTRY_IMAGE:build-cache
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      --build-arg VCS_NAME=$CI_PROJECT_NAME
      --build-arg VCS_URL=$CI_PROJECT_URL
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_REF_SHORT=$CI_COMMIT_SHORT_SHA
      --build-arg VCS_VER=$CI_COMMIT_REF_NAME
      --build-arg VCS_ID=$CI_PROJECT_ID
      --build-arg VCS_NAMESPACE=$CI_PROJECT_NAMESPACE
      . | tee -a ci-build.log
    - docker push $CI_REGISTRY_IMAGE:build-cache
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ci-build.log

### PUSH ###
push:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: none
  stage: push
  only:
    - master
  script:
    - CI_IMAGE_TAG=$(if [ ${CI_COMMIT_REF_NAME} == master ]; then echo latest; else echo $CI_COMMIT_REF_NAME; fi)
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_IMAGE_TAG
