version: '3.6'

x-default: &node
  build:
    context: .
    dockerfile: Dockerfile
  image: ${CCAO_REGISTRY_URL}/services/service_sqoop_iasworld:latest
  volumes:
    - ./drivers:/jdbc
    - ./scripts:/scripts
    - ./target:/tmp/target
  environment:
    - MASTER_HOSTNAME=sqoop-node-master
    # - NODE_HOSTNAMES=sqoop-node-2 sqoop-node-3 sqoop-node-4
    - IPTS_HOSTNAME
    - IPTS_PORT
    - IPTS_SERVICE_NAME
    - IPTS_USERNAME
    - IPTS_TABLE
  secrets:
    - IPTS_PASSWORD
  networks:
    - hadoopnet

services:
  sqoop-node-master:
    <<: *node
    container_name: sqoop-node-master
    hostname: sqoop-node-master
    ports:
      - 9870:9870
      - 9864:9864
      - 8081:8080
      - 8082:8088
      - 8042:8042
    command: >
      /bin/bash -c "/scripts/wait-for-it.sh hive-metastore-server:9083 --
                    /scripts/run-sqoop.sh"

  # Other datanodes disabled by default since they can cause issues with
  # memory management when running on the same machine
  # sqoop-node-2:
  #   <<: *node
  #   container_name: sqoop-node-2
  #   command: tail -f /dev/null
  #   depends_on: 
  #     - sqoop-node-master

  # sqoop-node-3:
  #   <<: *node
  #   container_name: sqoop-node-3
  #   command: tail -f /dev/null
  #   depends_on: 
  #     - sqoop-node-master

  # sqoop-node-4:
  #   <<: *node
  #   container_name: sqoop-node-4
  #   command: tail -f /dev/null
  #   depends_on: 
  #     - sqoop-node-master

  hive-metastore-postgresql:
    container_name: hive-metastore-postgresql
    hostname: hive-metastore-postgresql
    image: postgres:9.5.3
    volumes:
      - ./docker-config/hive/:/docker-entrypoint-initdb.d/
    networks:
      - hadoopnet
    depends_on: 
      - sqoop-node-master

  hive-metastore-server:
    <<: *node
    container_name: hive-metastore-server
    hostname: hive-metastore-server
    depends_on: 
      - sqoop-node-master
    environment:
      - MASTER_HOSTNAME=sqoop-node-master
      - SKIP_BOOTSTRAP=1
    command: >
      /bin/bash -c "/scripts/wait-for-it.sh hive-metastore-postgresql:5432 --
                    schematool -initSchema -dbType postgres
                    hive --service metastore"

networks:
  hadoopnet:
    ipam:
      config:
        - subnet: 211.54.0.0/16
    name: hadoopnet

secrets:
  IPTS_PASSWORD:
    file: secrets/IPTS_PASSWORD
