version: '3.6'
services:
  sqoop:
    build: .
    image: sqoop:latest 
    container_name: sqoop
    volumes:
      - ./drivers:/jdbc
      - ./scripts:/scripts
      - ./target:/tmp/target
      - ./target/metastore:/root/.sqoop
    environment:
      - IPTS_HOSTNAME
      - IPTS_PORT
      - IPTS_SERVICE_NAME
      - IPTS_USERNAME
    secrets:
      - IPTS_PASSWORD

secrets:
  IPTS_PASSWORD:
    file: secrets/IPTS_PASSWORD
