CREATE TABLE `iasworld.enter`(
  `jur` string,
  `parid` string,
  `enterdt` string,
  `entercd` string,
  `enterid` string,
  `enterinfo` string,
  `who` string,
  `wen` string,
  `user1` string,
  `user2` string,
  `user3` string,
  `user4` string,
  `user5` string,
  `user6` string,
  `note1` string,
  `note2` string,
  `iasw_id` numeric,
  `trans_id` numeric,
  `upd_status` string,
  `seq` numeric,
  `cur` string,
  `deactivat` string,
  `loaded_at` string)
STORED AS PARQUET
TBLPROPERTIES ('parquet.compression'='SNAPPY');
