CREATE TABLE `iasworld.lpmod`(
  `ver` string,
  `ltype` string,
  `lcode` string,
  `nmod` numeric,
  `zmod` numeric,
  `lmod` numeric,
  `smod` numeric,
  `umod` numeric,
  `bsize` numeric,
  `brate` numeric,
  `bincr` numeric,
  `bdecr` numeric,
  `who` string,
  `wen` string,
  `depthtble` string,
  `modtype` string,
  `acretble` numeric,
  `adjltype` string,
  `acradjflg` string,
  `iasw_id` numeric,
  `soiltble` string,
  `schedtble` numeric,
  `loaded_at` string)
STORED AS PARQUET
TBLPROPERTIES ('parquet.compression'='SNAPPY');
