CREATE TABLE `iasworld.lpmod`(
  `ver` varchar,
  `ltype` varchar,
  `lcode` varchar,
  `nmod` decimal,
  `zmod` decimal,
  `lmod` decimal,
  `smod` decimal,
  `umod` decimal,
  `bsize` decimal,
  `brate` decimal,
  `bincr` decimal,
  `bdecr` decimal,
  `who` varchar,
  `wen` string,
  `depthtble` varchar,
  `modtype` varchar,
  `acretble` decimal,
  `adjltype` varchar,
  `acradjflg` varchar,
  `iasw_id` decimal,
  `soiltble` varchar,
  `schedtble` decimal,
  `loaded_at` string)
STORED AS PARQUET
TBLPROPERTIES ('parquet.compression'='ZSTD');
