CREATE TABLE `iasworld.valclass`(
  `jur` varchar,
  `rolltype` varchar,
  `valclass` varchar,
  `class` varchar,
  `luc` varchar,
  `vclass` varchar,
  `who` varchar,
  `wen` string,
  `ratio1` decimal,
  `ratio2` decimal,
  `ratio3` decimal,
  `user1` varchar,
  `user2` varchar,
  `user3` varchar,
  `user4` varchar,
  `user5` varchar,
  `user6` varchar,
  `user7` varchar,
  `user8` varchar,
  `user9` varchar,
  `user10` varchar,
  `assess_pct` decimal,
  `user11` varchar,
  `user12` varchar,
  `user13` varchar,
  `user14` varchar,
  `user15` varchar,
  `iasw_id` decimal,
  `loaded_at` string)
PARTITIONED BY (`taxyr` string)
STORED AS PARQUET
TBLPROPERTIES ('parquet.compression'='ZSTD');
