sqoop job -libjars /tmp/bindir/ -jt local --fs file:/// \
    --create TESTJOB -- import \
    --bindir /tmp/bindir/ \
    --connect jdbc:oracle:thin:@//${IPTS_HOSTNAME}:${IPTS_PORT}/${IPTS_SERVICE_NAME} \
    --username ${IPTS_USERNAME} \
    --password-file /run/secrets/IPTS_PASSWORD \
    --table "IASWORLD.${IPTS_TABLE}" \
    --split-by TAXYR \
    --target-dir /tmp/target/${IPTS_TABLE} \
    --delete-target-dir \
    --as-parquetfile
