on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  release:
    types: [published]

name: docker-build

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag
        run: echo "IMAGE_TAG=$(if [ ${{ github.ref_name }} == master ]; then echo latest; else echo ${{ github.ref_name }}; fi)" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
